const ADD_PERSONAL_DATA = 'ADD_PERSONAL_DATA'
const RESET_PERSONAL_DATA = 'RESET_PERSONAL_DATA'
const SET_PERSONAL_DATA = 'SET_PERSONAL_DATA'

export default {
    ADD_PERSONAL_DATA,
    RESET_PERSONAL_DATA,
    SET_PERSONAL_DATA
}
