const ADD_WORKPLACE = 'ADD_WORKPLACE'
const RESET_WORKPLACES = 'RESET_WORKPLACES'
const SET_EXPERIENCE = 'SET_EXPERIENCE'

export default {
    ADD_WORKPLACE,
    RESET_WORKPLACES,
    SET_EXPERIENCE
}
