const ADD_INTEREST = 'ADD_INTEREST'
const RESET_INTERESTS = 'RESET_INTERESTS'
const SET_INTERESTS = 'SET_INTERESTS'

export default {
    ADD_INTEREST,
    RESET_INTERESTS,
    SET_INTERESTS
}
